import type { HullDef, MountDef } from './types.ts';

// The Compact's M1 hulls. Ship frame: +x forward, +y port.

const mount = (m: MountDef): MountDef => m;
const turret = (id: string, size: 1 | 2 | 3, x: number, y = 0): MountDef =>
  mount({ id, zone: 'dorsal', size, type: 'hardpoint', x, y, facing: 0, arc: 150 });
const core = (id: string, size: 1 | 2 | 3, x: number): MountDef =>
  mount({ id, zone: 'core', size, type: 'internal', x, y: 0, facing: 0, arc: 0 });
const engine = (id: string, size: 1 | 2 | 3, x: number, y = 0): MountDef =>
  mount({ id, zone: 'stern', size, type: 'engine', x, y, facing: 180, arc: 0 });

export const HULLS: readonly HullDef[] = [
  {
    id: 'picket',
    name: 'Picket',
    cls: 'frigate',
    faction: 'compact',
    length: 60,
    beam: 16,
    height: 9,
    radius: 22,
    baseMass: 380,
    structure: 420,
    turnBase: 80,
    refAccel: 10,
    cost: 180,
    crew: 10,
    armourMax: [60, 40, 40, 30],
    armourMass: [0.5, 1.2, 1.2, 0.5],
    mounts: [
      mount({ id: 'B1', zone: 'bow', size: 2, type: 'hardpoint', x: 24, y: 0, facing: 0, arc: 60 }),
      turret('D1', 1, 12),
      core('C1', 2, -12),
      core('C2', 1, 2),
      engine('E1', 2, -29),
    ],
  },
  {
    id: 'lancet',
    name: 'Lancet',
    cls: 'frigate',
    faction: 'compact',
    length: 64,
    beam: 18,
    height: 9,
    radius: 24,
    baseMass: 420,
    structure: 450,
    turnBase: 75,
    refAccel: 10,
    cost: 200,
    crew: 12,
    armourMax: [60, 40, 40, 30],
    armourMass: [0.5, 1.3, 1.3, 0.5],
    mounts: [
      mount({ id: 'B1', zone: 'bow', size: 2, type: 'hardpoint', x: 26, y: 0, facing: 0, arc: 45 }),
      mount({ id: 'B2', zone: 'bow', size: 1, type: 'hardpoint', x: 15, y: 0, facing: 0, arc: 60 }),
      turret('D1', 1, -5),
      core('C1', 2, -16),
      core('C2', 1, 5),
      engine('E1', 2, -31),
    ],
  },
  {
    id: 'warden',
    name: 'Warden',
    cls: 'destroyer',
    faction: 'compact',
    length: 100,
    beam: 26,
    height: 14,
    radius: 36,
    baseMass: 1100,
    structure: 1140,
    turnBase: 45,
    refAccel: 8,
    cost: 450,
    crew: 30,
    armourMax: [80, 60, 60, 40],
    armourMass: [1.2, 2.8, 2.8, 1.2],
    mounts: [
      mount({ id: 'B1', zone: 'bow', size: 2, type: 'hardpoint', x: 42, y: 0, facing: 0, arc: 45 }),
      turret('D1', 2, 16),
      turret('D2', 2, -26),
      mount({ id: 'P1', zone: 'port', size: 1, type: 'hardpoint', x: 4, y: 12, facing: 90, arc: 70 }),
      mount({ id: 'S1', zone: 'starboard', size: 1, type: 'hardpoint', x: 4, y: -12, facing: -90, arc: 70 }),
      core('C1', 3, -10),
      core('C2', 2, 4),
      core('C3', 1, 30),
      engine('E1', 2, -48, 7),
      engine('E2', 2, -48, -7),
    ],
  },
  {
    id: 'bastion',
    name: 'Bastion',
    cls: 'cruiser',
    faction: 'compact',
    length: 170,
    beam: 44,
    height: 22,
    radius: 62,
    baseMass: 3400,
    structure: 3300,
    turnBase: 22,
    refAccel: 6,
    cost: 1100,
    crew: 60,
    armourMax: [110, 80, 80, 50],
    armourMass: [3, 7, 7, 3],
    mounts: [
      mount({ id: 'B1', zone: 'bow', size: 3, type: 'hardpoint', x: 74, y: 0, facing: 0, arc: 40 }),
      turret('D1', 3, 40),
      turret('D2', 2, -42),
      mount({ id: 'P1', zone: 'port', size: 2, type: 'hardpoint', x: 20, y: 20, facing: 90, arc: 70 }),
      mount({ id: 'P2', zone: 'port', size: 2, type: 'hardpoint', x: -16, y: 20, facing: 90, arc: 70 }),
      mount({ id: 'S1', zone: 'starboard', size: 2, type: 'hardpoint', x: 20, y: -20, facing: -90, arc: 70 }),
      mount({ id: 'S2', zone: 'starboard', size: 2, type: 'hardpoint', x: -16, y: -20, facing: -90, arc: 70 }),
      core('C1', 3, -18),
      core('C2', 3, 2),
      core('C3', 2, 22),
      core('C4', 1, 58),
      engine('E1', 3, -82, 12),
      engine('E2', 3, -82, -12),
    ],
  },
];

export const HULL_BY_ID: ReadonlyMap<string, HullDef> = new Map(HULLS.map((h) => [h.id, h]));
