import type { ModuleDef } from './types.ts';

// The Compact's M1 module set. Tables in docs/design/m1-rules.md §2.

const base = { draw: 0, output: 0, thrust: 0 };

export const MODULES: readonly ModuleDef[] = [
  {
    ...base,
    id: 'ac-s',
    name: 'Autocannon S',
    code: 'AC-S',
    kind: 'weapon',
    size: 1,
    mount: 'hardpoint',
    mass: 20,
    draw: 2,
    cost: 30,
    hp: 60,
    crew: 4,
    weapon: { family: 'kinetic', damage: 4, pen: 12, reload: 0.4, range: 900, tracking: 40, spread: 0.02 },
    blurb: 'Fast-slewing light cannon. Hits small craft; barely scratches heavy plate.',
  },
  {
    ...base,
    id: 'ac-m',
    name: 'Autocannon M',
    code: 'AC-M',
    kind: 'weapon',
    size: 2,
    mount: 'hardpoint',
    mass: 45,
    draw: 4,
    cost: 60,
    hp: 100,
    crew: 8,
    weapon: { family: 'kinetic', damage: 7, pen: 16, reload: 0.5, range: 1100, tracking: 28, spread: 0.014 },
    blurb: 'Twin autocannon. The standard answer to raiders.',
  },
  {
    ...base,
    id: 'md-m',
    name: 'Mass Driver M',
    code: 'MD-M',
    kind: 'weapon',
    size: 2,
    mount: 'hardpoint',
    mass: 80,
    draw: 10,
    cost: 110,
    hp: 120,
    crew: 8,
    weapon: { family: 'kinetic', damage: 28, pen: 45, reload: 3.0, range: 1600, tracking: 10, spread: 0.006 },
    blurb: 'Coil-fed slug thrower. Good penetration, slow to track.',
  },
  {
    ...base,
    id: 'hg-l',
    name: 'Heavy Gun L',
    code: 'HG-L',
    kind: 'weapon',
    size: 3,
    mount: 'hardpoint',
    mass: 170,
    draw: 14,
    cost: 190,
    hp: 220,
    crew: 16,
    weapon: { family: 'kinetic', damage: 36, pen: 55, reload: 2.2, range: 1700, tracking: 14, spread: 0.008 },
    blurb: 'Turreted twin gun. A compromise between reach, punch and tracking.',
  },
  {
    ...base,
    id: 'md-l',
    name: 'Mass Driver L',
    code: 'MD-L',
    kind: 'weapon',
    size: 3,
    mount: 'hardpoint',
    mass: 200,
    draw: 22,
    cost: 240,
    hp: 240,
    crew: 16,
    weapon: { family: 'kinetic', damage: 70, pen: 80, reload: 5.0, range: 2200, tracking: 5, spread: 0.004 },
    blurb: 'Capital slug thrower. Goes through anything it hits. Hits little that moves.',
  },
  { ...base, id: 'reactor-s', name: 'Reactor S', code: 'RX-S', kind: 'reactor', size: 1, mount: 'internal', mass: 60, output: 20, cost: 60, hp: 120, crew: 6, blurb: 'Breaches in 15% of losses.' },
  { ...base, id: 'reactor-m', name: 'Reactor M', code: 'RX-M', kind: 'reactor', size: 2, mount: 'internal', mass: 140, output: 45, cost: 120, hp: 200, crew: 10, blurb: 'Breaches in 25% of losses.' },
  { ...base, id: 'reactor-l', name: 'Reactor L', code: 'RX-L', kind: 'reactor', size: 3, mount: 'internal', mass: 320, output: 100, cost: 230, hp: 360, crew: 18, blurb: 'Breaches in 35% of losses. Keep it deep.' },
  { ...base, id: 'drive-s', name: 'Drive S', code: 'DR-S', kind: 'drive', size: 1, mount: 'engine', mass: 40, draw: 4, thrust: 5000, cost: 40, hp: 100, crew: 3, blurb: 'Fusion drive bell.' },
  { ...base, id: 'drive-m', name: 'Drive M', code: 'DR-M', kind: 'drive', size: 2, mount: 'engine', mass: 90, draw: 8, thrust: 10000, cost: 80, hp: 180, crew: 6, blurb: 'Fusion drive bell.' },
  { ...base, id: 'drive-l', name: 'Drive L', code: 'DR-L', kind: 'drive', size: 3, mount: 'engine', mass: 200, draw: 16, thrust: 22000, cost: 160, hp: 320, crew: 12, blurb: 'Fusion drive bell.' },
  { ...base, id: 'bridge', name: 'Bridge', code: 'BRG', kind: 'bridge', size: 1, mount: 'internal', mass: 25, draw: 2, cost: 40, hp: 120, crew: 20, blurb: 'Required. Lose it and the ship is out of the fight.' },
  { ...base, id: 'fire-control', name: 'Fire Control', code: 'FCS', kind: 'firecontrol', size: 1, mount: 'internal', mass: 20, draw: 4, cost: 70, hp: 80, crew: 6, blurb: '+25% tracking for every weapon on the ship. One per ship counts.' },
  { ...base, id: 'damage-control', name: 'Damage Control', code: 'DCT', kind: 'damagecontrol', size: 2, mount: 'internal', mass: 50, draw: 5, cost: 90, hp: 140, crew: 24, blurb: 'Re-plates worn facings and patches modules. 400 points of supplies.' },
];

export const MODULE_BY_ID: ReadonlyMap<string, ModuleDef> = new Map(MODULES.map((m) => [m.id, m]));
export const MODULE_INDEX: ReadonlyMap<string, number> = new Map(MODULES.map((m, i) => [m.id, i]));
